version: '3'
services:
    eureka:
        image: ${DOCKER_REGISTRY:-}${DOCKER_REPO:-}eureka:${VERSION}
        restart: always
        container_name: eureka
        hostname: eureka
        expose:
            - "8761"
        ports:
            - 8761:8761
    config-server:
        image: ${DOCKER_REGISTRY:-}${DOCKER_REPO:-}config-server:${VERSION}
        restart: always
        container_name: config-server
        hostname: config-server
        depends_on:
          - eureka
        links:
          - eureka
        expose:
            - "8888"
        ports:
            - 8888:8888
    product-service:
        image: ${DOCKER_REGISTRY:-}${DOCKER_REPO:-}product-service:${VERSION}
        restart: always
        container_name: product-service
        hostname: product-service
        ports:
            - 8081:8081
        links:
            - product-service-db
            - eureka
            - config-server
        depends_on:
            - product-service-db
            - eureka
            - config-server
    product-service-db:
        restart: always
        container_name: product-service-db
        image: mysql
        expose:
            - "3306"
        volumes:
            - ./services/product-service/deployment/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: product_service
            MYSQL_USER: root
            MYSQL_PASSWORD: root