version: '3'
services:
    eureka:
        restart: always
        container_name: eureka
        hostname: eureka
        build:
            context: ./eureka
            dockerfile: deployment/Dockerfile
        expose:
            - "8761"
        ports:
            - 8761:8761
    config-server:
        restart: always
        container_name: config-server
        hostname: config-server
        depends_on:
          - eureka
        links:
          - eureka
        build:
            context: ./config-server
            dockerfile: deployment/Dockerfile
        expose:
            - "8888"
        ports:
            - 8888:8888
    product-service:
        restart: always
        container_name: product-service
        hostname: product-service
        build:
            context: ./product-service
            dockerfile: deployment/Dockerfile
        ports:
            - 8081:8081
        links:
            - product-service-db
            - eureka
            - config-server
        depends_on:
            - product-service-db
            - eureka
            - config-server
    product-service-db:
        restart: always
        container_name: product-service-db
        image: mysql
        expose:
            - "3306"
        volumes:
            - ./product-service/deployment/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: product_service
            MYSQL_USER: root
            MYSQL_PASSWORD: root