spring:
  application:
    name: product-service

---
server:
  port: 8081
spring:
  profiles: default
  datasource:
    url: jdbc:mysql://localhost:3306/product_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: local
  cloud:
    config:
      uri: http://localhost:8888

---
spring:
  profiles: docker
  cloud:
    config:
      uri: http://config-server:8888