server:
  port: ${NODEJS_SERVICE_SIDECAR_PORT:8082}

sidecar:
  port: ${NODEJS_SERVICE_PORT:3000}
  home-page-uri: http://localhost:${sidecar.port}/
  health-uri: http://localhost:${sidecar.port}/health

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE_HOST:localhost}:${EUREKA_SERVICE_PORT:8761}/eureka/
