server:
  port: ${PRODUCT_SERVICE_PORT:8081}

spring:
  datasource:
      url: jdbc:mysql://${PRODUCT_SERVICE_DB_HOST:localhost}:${PRODUCT_SERVICE_DB_PORT:3306}/${PRODUCT_SERVICE_DB_NAME:product_service}
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE_HOST:localhost}:${EUREKA_SERVICE_PORT:8761}/eureka/

logging:
  level:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG
